version: '3.8'
services:
  seq:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: "Y"
    volumes:
      - C:/DockerVolumes/seq/data:/data
    ports:
      - "5341:80"
    restart: unless-stopped
