@Ambition.UI_HostAddress = https://localhost:7289

GET {{Ambition.UI_HostAddress}}/maintenance-plan/4db30db9-0fc1-4cf7-8b39-94f1ef719c70
Accept: application/json

###
POST {{Ambition.UI_HostAddress}}/maintenance-plan
Accept: application/json
Content-Type: application/json

{
  "productId": "45a340d8-7bd1-4f56-95b3-8ca192ef6094",
  "customerId": "4f8b1c36-047b-4c5c-99e4-bf5446856d14",
  "description": "My Description",
  "userName": "matte",
  "effectiveOn": "2024-03-20T13:10:01.016Z"
}
###
